/home/pasquale/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/pasquale/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:nli-debug-cli.py:Command line: --has-bos --has-unk --batch-size 128 --restore models/snli/dam_1/acl/batch_dsearch_reg_v2_001/dam_1_001_15 -d data/snli/acl/v1/v1.2_edited.jsonl.gz
INFO:nli-debug-cli.py:Data size: 192
Traceback (most recent call last):
  File "./bin/nli-debug-cli.py", line 444, in <module>
    main(sys.argv[1:])
  File "./bin/nli-debug-cli.py", line 98, in main
    with open('{}_index_to_token.p'.format(restore_path), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/snli/dam_1/acl/batch_dsearch_reg_v2_001/dam_1_001_15_index_to_token.p'
